### ISSUE TITLE
Error running Thames

### ISSUE THREAD

**Issue by ptester8** [pro-xie/thames#1]
getting AttributeError: 'Namespace' object has no attribute 'key'
I have got an key from serpstack. 
C:\thames-master\thames-master>py -3 thames.py -k xxx4d14b82d2ff88c2695bxxxxxxxxxx -d "intitle: wordpress, site:.wordpress.com" -p 15 -v

**Comment by ptester8** [comment]
Any possible solution to this please.

**Comment by bad-bit** [comment]
Will triage the issue and post back the solution. Please allow some time

**Comment by bad-bit** [comment]
> 
> 
> Any possible solution to this please.

I didn't face any issue while executing with the same parameters. Please refer the attached screenshot.
Can you please purge the cloned directory and re-clone and run?
Also make sure that the key usage hasn't been exhausted.

If the issue persists, please attach a screenshot of the error. Will be easier to debug, thanks. :)
![output-20Jul2020_2](https://user-images.githubusercontent.com/27206809/87925985-afb8f880-ca9e-11ea-99f2-a3c9069a3a24.jpg)

**Comment by bad-bit** [comment]
> 
> 
> Any possible solution to this please.

Closing the issue as triaged and no issues found.
Feel free to open a separate issue if you face any problem. :)

**Comment by bad-bit** [comment]
Triaged, no issues found.
